version: '3.1'

services:
  zookeeper:
    image: zookeeper
    restart: always
    tmpfs: "/datalog"
    ports:
      - 2181:2181
  kafka:
    build: kafka-node
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOSTNAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECTION: zookeeper:2181